import { TestExamResponse } from './models';

export const QUESTION_TYPE = {
  CHOOSE_ANSWER: 'choose-answer',
  LISTENING_CHOOSE_ANSWER: 'choose-answer-listening',
  CHOOSE_TWO_ANSWER_LISTENING: 'choose-two-answer-listening',
  ANSWER_PARAGRAPH_LISTENING: 'answer-paragraph-listening',
  CHOOSE_CHARACTER_ANSWER: 'choose-character-answer',
  CHOOSE_TWO_ANSWER: 'choose-two-answer',
  ANSWER_PARAGRAPH: 'answer-paragraph',
  ANSWER_CHARACTER: 'answer-character',
  ANSWER_CHARACTER_LISTENING: 'answer-character-listening',
  ANSWER_QUESTION_LISTENING: 'answer-question-listening',
  ANSWER_SENTENCE_LISTENING: 'answer-sentence-listening',
  ANSWER_ONLY_INPUT: 'answer-only-input',
};

export const DATA_WRITING_CONTENT = [1, 2].map((item) => ({
  id: item,
  subId: item,
  part: item,
  numberOrder: item,
  type: '',
  questionTitle: null,
  text: null,
  lastText: null,
  isDownLine: null,
  options: null,
  value: '',
  isAnswer: false,
  isReview: false,
}));

export const DATA_MOCK_LISTENING: TestExamResponse = {
  displayQuestionDataResponse: {
    '1': {
      leftContent: [
        {
          id: null,
          subId: null,
          part: 1,
          type: 'unknown-listening',
          numberOrder: 1,
          questionTitle: null,
          text: ' **SECTION 1**\n\n ',
          lastText: '',
          isDownLine: false,
          options: null,
        },
      ],
      rightContent: [
        {
          id: 1,
          subId: 1,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' Complete the notes below.\n\nWrite **ONE WORD AND/OR A NUMBER** for each answer.\n\n\n\n<div class="title">Riverdale Pre-school</div>\n\n **Classes:**\n\nFirst group - Mrs. Oliver.\n\nSecond group - Mrs. ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 2,
          subId: 2,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: '.\n\n**Hours &Days**:\n\nSuzie will attend 3 days a week for a total of ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 3,
          subId: 3,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' hours\n\n**Activities**:\n\n<u>Outside time</u>\n\n\\- running, playing, or something quieter\n\n\\- just got a new piece of equipment\n\n\\- intend to make a ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 4,
          subId: 4,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: '.\n\n<u>Indoors</u>\n\n\\- this year, ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 5,
          subId: 5,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' activities are popular\n\n\\- they hear a ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 6,
          subId: 6,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: 'every day.\n\n**Fees**:\n\nNow costs $',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 7,
          subId: 7,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' per term\n\nFees include：\n\n\\- a trip to a ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 8,
          subId: 8,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' this year\n\n\\- chance to take home a ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 9,
          subId: 9,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: " every week\n\n**Don't forget**： **.**\n\n\\- Put a ",
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
        {
          id: 10,
          subId: 10,
          part: 1,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' , in Suzie’s bag\n\n**\\-** Arrange a visit; phone number: ',
          lastText: '. ',
          isDownLine: false,
          options: null,
        },
      ],
    },
    '2': {
      leftContent: [
        {
          id: null,
          subId: null,
          part: 2,
          type: 'unknown-listening',
          numberOrder: 1,
          questionTitle: null,
          text: ' **SECTION 2**\n\n ',
          lastText: '',
          isDownLine: false,
          options: null,
        },
      ],
      rightContent: [
        {
          id: 11,
          subId: 11,
          part: 2,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' Complete the sentences below.\n\nWrite **NO MORE THAN TWO WORDS AND/ORA NUMBER** for each answer.\n\nSpecial conditions may apply to ',
          lastText: ' regularly advertises new jobs.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 12,
          subId: 12,
          part: 2,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' students looking for a job.\n\nThe university Job Centre is located on the ',
          lastText: ' regularly advertises new jobs.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 13,
          subId: 13,
          part: 2,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' Campus.\n\nThe Job Centre remains open until ',
          lastText: ' regularly advertises new jobs.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 14,
          subId: 14,
          part: 2,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' every evening.\n\nThe only day the employment lawyer is available is ',
          lastText: ' regularly advertises new jobs.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 15,
          subId: 15,
          part: 2,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' .\n\nThe university ',
          lastText: ' regularly advertises new jobs.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 16,
          subId: 16,
          part: 2,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'At present, the university is offering part-time work in',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'its offices.',
            },
            {
              value: 'B',
              title: 'the IT centre.',
            },
            {
              value: 'C',
              title: 'the car parks.',
            },
          ],
        },
        {
          id: 17,
          subId: 17,
          part: 2,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'Local employers visit the university',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'only in the first term.',
            },
            {
              value: 'B',
              title: 'twice a term,',
            },
            {
              value: 'C',
              title: 'throughout the year.',
            },
          ],
        },
        {
          id: 18,
          subId: 18,
          part: 2,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'According to the speaker, a part-time job can',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'lead to a full-time job after graduation.',
            },
            {
              value: 'B',
              title: 'provide a useful work record for the future.',
            },
            {
              value: 'C',
              title: 'give the chance to develop team-work skills.',
            },
          ],
        },
        {
          id: 19,
          subId: 19,
          part: 2,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'Students who work part-time',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'will be taxed.',
            },
            {
              value: 'B',
              title: 'will be paid every week.',
            },
            {
              value: 'C',
              title: 'will need private insurance.',
            },
          ],
        },
        {
          id: 20,
          subId: 20,
          part: 2,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'Part-time student workers are advised to',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'give notice in writing.',
            },
            {
              value: 'B',
              title: 'communicate by email.',
            },
            {
              value: 'C',
              title: 'have a mobile phone.',
            },
          ],
        },
      ],
    },
    '3': {
      leftContent: [
        {
          id: null,
          subId: null,
          part: 3,
          type: 'unknown-listening',
          numberOrder: 1,
          questionTitle: null,
          text: ' SECTION 3\n\n ',
          lastText: '',
          isDownLine: false,
          options: null,
        },
      ],
      rightContent: [
        {
          id: 21,
          subId: 21,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle: 'How did John choose the topic of his research project?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'He thought the information would be useful for town planning.',
            },
            {
              value: 'B',
              title: 'He has a special interest in the use of public services.',
            },
            {
              value: 'C',
              title: 'He read about a similar study which had been done earlier.',
            },
          ],
        },
        {
          id: 22,
          subId: 22,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle: 'During his research, John is expecting to find that',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'the use of public services has altered very little.',
            },
            {
              value: 'B',
              title: 'a group of people has changed its habits.',
            },
            {
              value: 'C',
              title: 'the most frequently used facility is the library.',
            },
          ],
        },
        {
          id: 23,
          subId: 23,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle: 'What is the problem with using official records?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'They may be lacking in detail.',
            },
            {
              value: 'B',
              title: 'They may not be readily available.',
            },
            {
              value: 'C',
              title: 'They may be difficult to analyse.',
            },
          ],
        },
        {
          id: 24,
          subId: 24,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle:
            'What does the tutor think about John using a questionnaire to get information?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'He needs to do a course in questionnaire design first.',
            },
            {
              value: 'B',
              title: 'He should use this method instead of looking at public records.',
            },
            {
              value: 'C',
              title: 'He will find the practice he gets useful the following year.',
            },
          ],
        },
        {
          id: 25,
          subId: 25,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle: 'Which new variable does John agree to add to his investigation?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'occupation',
            },
            {
              value: 'B',
              title: 'income group',
            },
            {
              value: 'C',
              title: 'qualifications',
            },
          ],
        },
        {
          id: 26,
          subId: 26,
          part: 3,
          type: 'choose-answer-listening',
          numberOrder: 2,
          questionTitle: 'How many questionnaires will John distribute?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'the same number as in the previous study',
            },
            {
              value: 'B',
              title: 'a greater number than he needs for analysis',
            },
            {
              value: 'C',
              title: 'the number recommended in the project guidelines',
            },
          ],
        },
        {
          id: 27,
          subId: 27,
          part: 3,
          type: 'choose-two-answer-listening',
          numberOrder: 3,
          questionTitle:
            'Which **TWO** strategies will John use to encourage people to fill out his **questionnaire?**',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'using simple language',
            },
            {
              value: 'B',
              title: 'delivering the questionnaires in person',
            },
            {
              value: 'C',
              title: 'making the questionnaires anonymous',
            },
            {
              value: 'D',
              title: 'providing return envelopes',
            },
            {
              value: 'E',
              title: 'trialling the questionnaire on friends',
            },
          ],
        },
        {
          id: 28,
          subId: 27,
          part: 3,
          type: 'choose-two-answer-listening',
          numberOrder: 3,
          questionTitle:
            'Which **TWO** strategies will John use to encourage people to fill out his **questionnaire?**',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'using simple language',
            },
            {
              value: 'B',
              title: 'delivering the questionnaires in person',
            },
            {
              value: 'C',
              title: 'making the questionnaires anonymous',
            },
            {
              value: 'D',
              title: 'providing return envelopes',
            },
            {
              value: 'E',
              title: 'trialling the questionnaire on friends',
            },
          ],
        },
        {
          id: 29,
          subId: 29,
          part: 3,
          type: 'choose-two-answer-listening',
          numberOrder: 4,
          questionTitle:
            'Which **TWO** pieces of advice does the tutor give John about his questionnaire?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'There should be a mixture of question types.',
            },
            {
              value: 'B',
              title: 'Some questions should elicit personal information.',
            },
            {
              value: 'C',
              title: "There should be an introduction to explain the survey's purpose.",
            },
            {
              value: 'D',
              title: 'A telephone number should be provided for queries.',
            },
            {
              value: 'E',
              title: 'The questions should only take a few minutes to answer.',
            },
          ],
        },
        {
          id: 30,
          subId: 29,
          part: 3,
          type: 'choose-two-answer-listening',
          numberOrder: 4,
          questionTitle:
            'Which **TWO** pieces of advice does the tutor give John about his questionnaire?',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'There should be a mixture of question types.',
            },
            {
              value: 'B',
              title: 'Some questions should elicit personal information.',
            },
            {
              value: 'C',
              title: "There should be an introduction to explain the survey's purpose.",
            },
            {
              value: 'D',
              title: 'A telephone number should be provided for queries.',
            },
            {
              value: 'E',
              title: 'The questions should only take a few minutes to answer.',
            },
          ],
        },
      ],
    },
    '4': {
      leftContent: [
        {
          id: null,
          subId: null,
          part: 4,
          type: 'unknown-listening',
          numberOrder: 1,
          questionTitle: null,
          text: ' SECTION 4\n\n ',
          lastText: '',
          isDownLine: false,
          options: null,
        },
      ],
      rightContent: [
        {
          id: 31,
          subId: 31,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' Complete the sentences below.\n\nWrite **NO MORE THAN TWO WORDS** for each answer.\n\n\n\n<div class="title">Driverless vehicle competition</div>\n\n Undergraduates from both the engineering school and the ',
          lastText: '<u>, </u>\n\nlasers, and laptops to measure its surroundings.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 32,
          subId: 32,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: ' department can definitely take part in the project.\n\nThe automated vehicles will have to avoid obstacles such as ',
          lastText: '<u>, </u>\n\nlasers, and laptops to measure its surroundings.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 33,
          subId: 33,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 2,
          questionTitle: null,
          text: '.\n\nThe tutor mentions one vehicle which used technology such as ',
          lastText: '<u>, </u>\n\nlasers, and laptops to measure its surroundings.\n\n ',
          isDownLine: false,
          options: null,
        },
        {
          id: 34,
          subId: 34,
          part: 4,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'The purpose of holding the race is to',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'interest students in careers in industry.',
            },
            {
              value: 'B',
              title: 'help provide finance for universities.',
            },
            {
              value: 'C',
              title: 'find useful new design features.',
            },
          ],
        },
        {
          id: 35,
          subId: 35,
          part: 4,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: 'The tutor says success will depend on',
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'the software design.',
            },
            {
              value: 'B',
              title: 'good, solid construction.',
            },
            {
              value: 'C',
              title: 'sophisticated mechanisms.',
            },
          ],
        },
        {
          id: 36,
          subId: 36,
          part: 4,
          type: 'choose-answer-listening',
          numberOrder: 3,
          questionTitle: "This year's competitors were surprised that the vehicles",
          text: null,
          lastText: null,
          isDownLine: null,
          options: [
            {
              value: 'A',
              title: 'were so easy to design,',
            },
            {
              value: 'B',
              title: 'were as successful as they were.',
            },
            {
              value: 'C',
              title: 'took such a short time to construct.',
            },
          ],
        },
        {
          id: 37,
          subId: 37,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 4,
          questionTitle: null,
          text: '',
          lastText: ' . ',
          isDownLine: false,
          options: null,
        },
        {
          id: 38,
          subId: 38,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 4,
          questionTitle: null,
          text: ' .\n\n',
          lastText: ' . ',
          isDownLine: false,
          options: null,
        },
        {
          id: 39,
          subId: 39,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 4,
          questionTitle: null,
          text: ' .\n\n',
          lastText: ' . ',
          isDownLine: false,
          options: null,
        },
        {
          id: 40,
          subId: 40,
          part: 4,
          type: 'answer-paragraph-listening',
          numberOrder: 4,
          questionTitle: null,
          text: ' .\n\n',
          lastText: ' . ',
          isDownLine: false,
          options: null,
        },
      ],
    },
  },
  listTypeQuestion: {
    part1: ['unknown-listening', 'answer-paragraph-listening'],
    part2: ['unknown-listening', 'answer-paragraph-listening', 'choose-answer-listening'],
    part3: [
      'unknown-listening',
      'choose-answer-listening',
      'choose-two-answer-listening',
      'choose-two-answer-listening',
    ],
    part4: [
      'unknown-listening',
      'answer-paragraph-listening',
      'choose-answer-listening',
      'answer-paragraph-listening',
    ],
  },
  id: 2509,
  submitId: 2510,
  resourceId: 4,
};
